language: node_js
node_js:
  - '13'
script:
  - npm install
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
